#!/usr/bin/env python3
"""Generates src/catalogue.cpp from tools/rounds.csv.

Not a development tool: the catalogue is committed and the data is frozen. This exists so every
derived number in it is traceable to a documented relation rather than being a literal nobody can
check. tests/check_catalogue_generated.sh asserts the committed file still matches this output.

Relations, all justified in docs/catalogue-review.md:
  spin rate      60 V / (20 d)          1:20 calibre twist, spin-stabilised rounds only
  axial inertia  0.1391 m d^2           measured M107 ratio, not a uniform cylinder
  spin halflife  from roll damping       C_l_p = -0.015 at 0.6 of muzzle speed, 1.0 kg/m3
  C_M_alpha 3.7  and C_L_alpha 1.6      class-typical, and Sg lands near 1.3 at the muzzle
"""

import csv
import math
import pathlib
import sys

TWIST_CALIBRES = 20.0
AXIAL_INERTIA_RATIO = 0.1391
ROLL_DAMPING = 0.015
C_M_ALPHA = 3.7
C_L_ALPHA = 1.6

HEADER = '''#include "ballistics/pm/catalogue.h"

namespace Ballistics::PM {

namespace {

// Generated by tools/generate_catalogue.py from tools/rounds.csv. Do not edit by hand: the
// generator is the record of where each derived number comes from, and a test checks that this
// file still matches its output. See docs/catalogue-review.md.
//
// Every round is calibrated: published mass, diameter, length and muzzle velocity, with the drag
// form factor fitted to a published maximum range. No motor is declared anywhere, so the two
// rocket-assisted rounds are absent rather than present and wrong.
//

Catalogue seed() {
    Catalogue c;
'''

FOOTER = '''    return c;
}

} // namespace

Catalogue Catalogue::withBuiltins() {
    static const Catalogue builtins = seed();
    return builtins;
}

const Projectile* Catalogue::find(const std::string& id) const {
    const auto it = m_byId.find(id);
    return it == m_byId.end() ? nullptr : &it->second;
}

std::vector<std::string> Catalogue::ids() const {
    std::vector<std::string> out;
    out.reserve(m_byId.size());
    for (const auto& [id, _] : m_byId) {
        out.push_back(id);
    }
    return out;
}

void Catalogue::add(Projectile p) {
    m_byId.insert_or_assign(p.id, std::move(p));
}

bool Catalogue::remove(const std::string& id) {
    return m_byId.erase(id) > 0;
}

} // namespace Ballistics::PM
'''


def read_rounds(path):
    with open(path) as handle:
        lines = [line for line in handle if not line.startswith('#')]
    return list(csv.DictReader(lines))


def spin_halflife(mass, diameter, muzzle_speed, axial_inertia):
    area = math.pi * diameter * diameter / 4.0
    speed = 0.6 * muzzle_speed
    rate = 1.0 * speed * area * diameter * diameter * ROLL_DAMPING / (4.0 * axial_inertia)
    return math.log(2.0) / rate


def emit(round_):
    mass = float(round_['mass'])
    diameter = float(round_['diameter'])
    speed = float(round_['muzzle_speed'])
    spun = round_['stabilisation'] == 'spin'

    axial = AXIAL_INERTIA_RATIO * mass * diameter * diameter
    table = {'G1': 'g1', 'G7': 'g7', 'Shell': 'shell'}[round_['drag_family']]

    if spun:
        rpm = 60.0 * speed / (TWIST_CALIBRES * diameter)
        muzzle = f'{{.speed = {round_["muzzle_speed"]}, .spinRate = {rpm:.0f}, ' \
                 f'.spinDecayHalflife = {spin_halflife(mass, diameter, speed, axial):.1f}}}'
        aero = (f'        .spinAero = SpinAero{{.Ixx = {axial:.5f}, '
                f'.C_M_alpha = {C_M_ALPHA}, .C_L_alpha = {C_L_ALPHA}}},\n')
        forces = 'BALLISTIC_FORCES | Force::SpinDrift'
    else:
        muzzle = f'{{.speed = {round_["muzzle_speed"]}, .spinRate = 0.0, ' \
                 f'.spinDecayHalflife = 0.0}}'
        aero = ''
        forces = 'BALLISTIC_FORCES'

    quality = {'calibrated': 'Calibrated', 'estimated': 'Estimated',
               'placeholder': 'Placeholder'}[round_['quality']]

    note = (f'        // Form factor fitted to a published maximum range of '
            f'{round_["published_range"]} m ({round_["source"]}).\n')

    return (f'''    c.add(Projectile{{
        .id = "{round_['id']}",
        .name = "{round_['name']}",
        .role = "{round_['role']}",
        .geometry = {{.mass = {round_['mass']}, .diameter = {round_['diameter']}, '''
            f'''.length = {round_['length']}}},
        .muzzle = {muzzle},
{note}        .drag = DragTable::{table}({round_['form_factor']}),
{aero}        .forces = {forces},
        .quality = DataQuality::{quality},
    }});
''')


def main():
    root = pathlib.Path(__file__).resolve().parent.parent
    rounds = read_rounds(root / 'tools' / 'rounds.csv')
    body = '\n'.join(emit(r) for r in rounds)
    text = HEADER + '\n' + body + '\n' + FOOTER

    if len(sys.argv) > 1 and sys.argv[1] == '--check':
        existing = (root / 'src' / 'catalogue.cpp').read_text()
        if existing != text:
            print('src/catalogue.cpp does not match tools/generate_catalogue.py output')
            return 1
        print(f'catalogue matches its generator ({len(rounds)} rounds)')
        return 0

    (root / 'src' / 'catalogue.cpp').write_text(text)
    print(f'wrote src/catalogue.cpp ({len(rounds)} rounds)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
