#include "ballistics/pm/catalogue.h"

namespace Ballistics::PM {

namespace {

// Generated by tools/generate_catalogue.py from tools/rounds.csv. Do not edit by hand: the
// generator is the record of where each derived number comes from, and a test checks that this
// file still matches its output. See docs/catalogue-review.md.
//
// Every round is calibrated: published mass, diameter, length and muzzle velocity, with the drag
// form factor fitted to a published maximum range. No motor is declared anywhere, so the two
// rocket-assisted rounds are absent rather than present and wrong.
//

Catalogue seed() {
    Catalogue c;

    c.add(Projectile{
        .id = "Mortar60mm_HE",
        .name = "60mm M720 HE",
        .role = "HE",
        .geometry = {.mass = 1.68, .diameter = 0.060, .length = 0.293},
        .muzzle = {.speed = 241, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 3490 m (M224 mortar).
        .drag = DragTable::g1(0.8411),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Mortar60mm_SMK",
        .name = "60mm M722 Smoke WP",
        .role = "SMOKE",
        .geometry = {.mass = 1.42, .diameter = 0.060, .length = 0.293},
        .muzzle = {.speed = 225, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 3200 m (M224 zone 4).
        .drag = DragTable::g1(0.7101),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Mortar81mm_HE",
        .name = "81mm M821 HE",
        .role = "HE",
        .geometry = {.mass = 4.2, .diameter = 0.081, .length = 0.393},
        .muzzle = {.speed = 341, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 5650 m (M252 / L16).
        .drag = DragTable::g1(0.8896),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Mortar81mm_SMK",
        .name = "81mm M819 Smoke RP",
        .role = "SMOKE",
        .geometry = {.mass = 4.1, .diameter = 0.081, .length = 0.470},
        .muzzle = {.speed = 297, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 4900 m (M252 zone 4).
        .drag = DragTable::g1(0.8850),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Mortar81mm_ILL",
        .name = "81mm M853A1 Illumination",
        .role = "ILLUM",
        .geometry = {.mass = 4.65, .diameter = 0.081, .length = 0.571},
        .muzzle = {.speed = 285, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 5050 m (FM 23-90).
        .drag = DragTable::g1(0.8202),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Mortar120mm_HE",
        .name = "120mm M933 HE",
        .role = "HE",
        .geometry = {.mass = 14.5, .diameter = 0.120, .length = 0.670},
        .muzzle = {.speed = 332, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 7200 m (M120 mortar).
        .drag = DragTable::g1(0.7021),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Mortar120mm_SMK",
        .name = "120mm M929 Smoke WP",
        .role = "SMOKE",
        .geometry = {.mass = 14.9, .diameter = 0.120, .length = 0.695},
        .muzzle = {.speed = 340, .spinRate = 0.0, .spinDecayHalflife = 0.0},
        // Form factor fitted to a published maximum range of 7200 m (M120 zone 4).
        .drag = DragTable::g1(0.7810),
        .forces = BALLISTIC_FORCES,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Howitzer155mm_HE",
        .name = "155mm M795 HE",
        .role = "HE",
        .geometry = {.mass = 46.5, .diameter = 0.155, .length = 0.857},
        .muzzle = {.speed = 827, .spinRate = 16006, .spinDecayHalflife = 127.7},
        // Form factor fitted to a published maximum range of 22400 m (39 calibre tube).
        .drag = DragTable::shell(1.1302),
        .spinAero = SpinAero{.Ixx = 0.15540, .C_M_alpha = 3.7, .C_L_alpha = 1.6},
        .forces = BALLISTIC_FORCES | Force::SpinDrift,
        .quality = DataQuality::Calibrated,
    });

    c.add(Projectile{
        .id = "Howitzer155mm_SMK",
        .name = "155mm M825 Smoke WP",
        .role = "SMOKE",
        .geometry = {.mass = 44.0, .diameter = 0.155, .length = 0.803},
        .muzzle = {.speed = 684, .spinRate = 13239, .spinDecayHalflife = 146.1},
        // Form factor fitted to a published maximum range of 18000 m (effective range).
        .drag = DragTable::shell(1.0867),
        .spinAero = SpinAero{.Ixx = 0.14704, .C_M_alpha = 3.7, .C_L_alpha = 1.6},
        .forces = BALLISTIC_FORCES | Force::SpinDrift,
        .quality = DataQuality::Calibrated,
    });

    return c;
}

} // namespace

Catalogue Catalogue::withBuiltins() {
    static const Catalogue builtins = seed();
    return builtins;
}

const Projectile* Catalogue::find(const std::string& id) const {
    const auto it = m_byId.find(id);
    return it == m_byId.end() ? nullptr : &it->second;
}

std::vector<std::string> Catalogue::ids() const {
    std::vector<std::string> out;
    out.reserve(m_byId.size());
    for (const auto& [id, _] : m_byId) {
        out.push_back(id);
    }
    return out;
}

void Catalogue::add(Projectile p) {
    m_byId.insert_or_assign(p.id, std::move(p));
}

bool Catalogue::remove(const std::string& id) {
    return m_byId.erase(id) > 0;
}

} // namespace Ballistics::PM
